parameters:

    ccdn_user_profile.profile.repository.class:     CCDNUser\ProfileBundle\Repository\ProfileRepository

    ccdn_user_profile.profile.manager.class:        CCDNUser\ProfileBundle\Manager\ProfileManager

    ccdn_user_profile.profile.avatar.form.type.class:       CCDNUser\ProfileBundle\Form\Type\ProfileAvatarType
    ccdn_user_profile.profile.bio.form.type.class:          CCDNUser\ProfileBundle\Form\Type\ProfileBioType
    ccdn_user_profile.profile.contact.form.type.class:      CCDNUser\ProfileBundle\Form\Type\ProfileContactType
    ccdn_user_profile.profile.personal.form.type.class:     CCDNUser\ProfileBundle\Form\Type\ProfilePersonalType
    ccdn_user_profile.profile.signature.form.type.class:    CCDNUser\ProfileBundle\Form\Type\ProfileSignatureType
    
    
    ccdn_user_profile.profile.avatar.form.handler.class:    CCDNUser\ProfileBundle\Form\Handler\ProfileAvatarFormHandler
    ccdn_user_profile.profile.bio.form.handler.class:       CCDNUser\ProfileBundle\Form\Handler\ProfileBioFormHandler
    ccdn_user_profile.profile.contact.form.handler.class:   CCDNUser\ProfileBundle\Form\Handler\ProfileContactFormHandler
    ccdn_user_profile.profile.personal.form.handler.class:  CCDNUser\ProfileBundle\Form\Handler\ProfilePersonalFormHandler
    ccdn_user_profile.profile.signature.form.handler.class: CCDNUser\ProfileBundle\Form\Handler\ProfileSignatureFormHandler

    ccdn_user_profile.dashboard.integrator.class:   CCDNUser\ProfileBundle\Component\Dashboard\DashboardIntegrator
    
services:

    #
    # Repositories.
    #
    ccdn_user_profile.profile.repository:
        class: %ccdn_user_profile.profile.repository.class%
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - 'CCDNUser\ProfileBundle\Entity\Profile'
        
    #
    # Managers.
    #
    ccdn_user_profile.profile.manager:
        class:  %ccdn_user_profile.profile.manager.class%
        arguments:  [@doctrine, @service_container]
        
    #
    # Profile Forms.
    #
    ccdn_user_profile.profile.avatar.form.type:
        class:  %ccdn_user_profile.profile.avatar.form.type.class%
        arguments:  [@doctrine]
    ccdn_user_profile.profile.avatar.form.handler:
        class:  %ccdn_user_profile.profile.avatar.form.handler.class%
        arguments:  [@form.factory, @service_container, @ccdn_user_profile.profile.manager]
        
    ccdn_user_profile.profile.bio.form.type:
        class:  %ccdn_user_profile.profile.bio.form.type.class%
        arguments:  [@doctrine]
    ccdn_user_profile.profile.bio.form.handler:
        class:  %ccdn_user_profile.profile.bio.form.handler.class%
        arguments:  [@form.factory, @service_container, @ccdn_user_profile.profile.manager]

    ccdn_user_profile.profile.contact.form.type:
        class:  %ccdn_user_profile.profile.contact.form.type.class%
        arguments:  [@doctrine]
    ccdn_user_profile.profile.contact.form.handler:
        class:  %ccdn_user_profile.profile.contact.form.handler.class%
        arguments:  [@form.factory, @service_container, @ccdn_user_profile.profile.manager]
        
    ccdn_user_profile.profile.personal.form.type:
        class:  %ccdn_user_profile.profile.personal.form.type.class%
        arguments:  [@doctrine]
    ccdn_user_profile.profile.personal.form.handler:
        class:  %ccdn_user_profile.profile.personal.form.handler.class%
        arguments:  [@form.factory, @service_container, @ccdn_user_profile.profile.manager]
        
    ccdn_user_profile.profile.signature.form.type:
        class:  %ccdn_user_profile.profile.signature.form.type.class%
        arguments:  [@doctrine]
    ccdn_user_profile.profile.signature.form.handler:
        class:  %ccdn_user_profile.profile.signature.form.handler.class%
        arguments:  [@form.factory, @service_container, @ccdn_user_profile.profile.manager]
        
    #
    # Dashboard Integrator.
    #
    ccdn_user_profile.dashboard.integrator:
        class: %ccdn_user_profile.dashboard.integrator.class%
        arguments: [@service_container]
        tags:
            - { name: ccdn_component_dashboard.integrator }
